version: '3.8'

services:
  connections:
    build:
      context: ./connections
    ports:
      - "8081:8081"
    environment:
      - ENV=development

  core:
    build:
      context: ./core
    ports:
      - "8082:8082"
    environment:
      - ENV=development

  model:
    build:
      context: ./model
    ports:
      - "5000:5000"
    environment:
      - ENV=development

  projects:
    build:
      context: ./projects
    ports:
      - "8080:8080"
    environment:
      - ENV=development




